package hackerrank.dynamicprogramming.abbreviation;

import org.junit.Test;

import static hackerrank.dynamicprogramming.abbreviation.Solution.NO;
import static hackerrank.dynamicprogramming.abbreviation.Solution.YES;
import static hackerrank.dynamicprogramming.abbreviation.Solution.getOutput;
import static org.junit.Assert.*;

public class SolutionTest {

    @Test
    public void aIsLessThanB() throws Exception {
        assertEquals(NO, getOutput("a","bb"));
    }

    @Test
    public void bIsEmptyOrJustSpaces() throws Exception {
        assertEquals(NO, getOutput("aaa",""));
        assertEquals(NO, getOutput("aaa","  "));
    }

    @Test
    public void aEqualsIgnoreCaseB() throws Exception {
        assertEquals(YES, getOutput("AAA","AAA"));
        assertEquals(YES, getOutput("aaa","AAA"));
    }

    @Test
    public void aContainsB() throws Exception {
        assertEquals(YES, getOutput("xxAAAxx","AAA"));
        assertEquals(YES, getOutput("xxAAxxAxx","AAA"));
    }

    @Test
    public void test0() throws Exception {
        assertEquals(YES, getOutput("daBcd","ABC"));
    }

    @Test
    public void test1() throws Exception {
        assertEquals(YES, getOutput("Pi","P"));
        assertEquals(NO, getOutput("AfPZN","APZNC"));
        assertEquals(NO, getOutput("LDJAN","APZNC"));
        assertEquals(YES, getOutput("UMKFW","UMKFW"));
        assertEquals(NO, getOutput("KXzQ","K"));
        assertEquals(YES, getOutput("LIT","LIT"));
        assertEquals(YES, getOutput("QYCH","QYCH"));
        assertEquals(YES, getOutput("DFIQG","DFIQG"));
        assertEquals(NO, getOutput("sYOCa","YOCN"));
        assertEquals(NO, getOutput("JHMWY","HUVPW"));
    }

    @Test
    public void test9() throws Exception {
        assertEquals(YES, getOutput("OKXAJYPrZKNRQCLFKXJPJBXAEHYKXLIEIHLQYZPUNGELNKOZHsVLCPCXYSBURPRAWBAXBZBFBhCWBRNsTUNZIKriNYYPFXRNODZPCKNTTPCCZqvajmjtgxjjeafposdovrrzhkwesukvmlwbdzzlvvzyigpfvrhytcxpmbdytlkfzvnjnddpxxotsjfeuxdvmihwadpigjejtuyyrocbtlklkbsndmrpmekreqbbbznnyayzhvyjwlfqmxperliiforxddhwvectqoryxgvomhtjgizwdokbkrsbohupmkwcleetukcivqdbedyajoyglnaqzicuikmrjclfokypugvfgdfbdwpnccztmxwnyxdqrccrgoajwpyeeooesjvluyqdygiovqsrpudcjpriirnophewxcejanrbuqndxikaudmcaynpqmqpbhxwmfwuwwbvalglktmbbnleagsncvqgyduqclvnipxjkctqzatziewlccbyrukvnwuamahovdouwakuokwucexhmqvsilmsjgkqqwenmnxcyvjwjwqmflcpsjdjvagreajsmqjnpqjombmrhnvexfjsldjvapitqyajbypzqbrkladxfqiwsbwbm","OKXAJYPZKNRQCLFKXJPJBXAEHYKXLIEIHLQYZPUNGELNKOZHVLCPCXYSBURPRAWBAXBZBFBCWBRNTUNZIKNYYPFXRNODZPCKNTTPCCZ"));
        assertEquals(YES, getOutput("ZTLIvFUYHQXJJXOGUSOQMQULQXXIJJNSTAEaNGPMXGDMXYINbBKSGAPQWRJELeBFHXDSRFONZJRZVSQAkARSJUYGAJCZLHESLCISMQDUCYKAIKWQYCmPSRRiEVvSEYNMDBXGHCBEFTvFBPDDWGWMVLUQKUJFEAAOTDSOYZCXbCNXWRSACFPEBQFTJWFPNJvXYOKZTLGWzVxBChKLHzDBPXDUKLYOAIXYARSHYSTTZVDNWYDOiZxLgOYZVKYAfXJNXQUAFCHVSQAAIMPRNQNRXDPOSHIXVYCRRCLAKZRKMVMGKXLWCcSDDhSLLkMPKYVSCMSPHeuwtmakggqjednmhlcnikewdoyfipgkrygyswcyupdqjxpihgkvtofqjtmwkoqmqyowlqbngxohxgupknkjpdnrvzmdorpljnffvxxzbrpolnawqlhhaeljudqsnclfwffgnjkevqlqsjblmmxkzrfcyriubmfwggpwgcygwnhhncmyajdieabqmckqtloolhbezweycglmzoshpfoecvafgxh","ZTLIFUYHQXJJXOGUSOQMQULQXXIJJNSTAENGPMXGDMXYINBKSGAPQWRJELBFHXDSRFONZJRZVSQAARSJUYGAJCZLHESLCISMQDUCYKAIKWQYCPSRREVSEYNMDBXGHCBEFTFBPDDWGWMVLUQKUJFEAAOTDSOYZCXCNXWRSACFPEBQFTJWFPNJXYOKZTLGWVBCKLHDBPXDUKLYOAIXYARSHYSTTZVDNWYDOZLOYZVKYAXJNXQUAFCHVSQAAIMPRNQNRXDPOSHIXVYCRRCLAKZRKMVMGKXLWCSDDSLLMPKYVSCMSPH"));
        assertEquals(YES, getOutput("HSIOCQYGXOZBHKTVEXDLTNTLAMPDLOYRZZECYKVLKHYLGRHZBYMLPRIDJVWOMLDUYNUXBIGKRFJSUGZZIXHYNENHVZESEPKOGNCWQXDVEQANBTARFDLFRQPWUKLOATLCBZNENEZYAKBMMFUUKDIWOUGMGJLLBENJCSNCAMGOGIBOGTSPPDDUBNOTZYFNNFYZHGZLQZIJYYYQPOATXZEOOUGDELMPOSNGUFPMISGRIWRTUTZJTFGPUSEEKRIFPKZZYMKBACEMNPAYSIFVTDCWOHGQTEYSPADCMFXRKJRZTBDGJSDCGWQIMBWNPYSCYEIBEQYLVSLGFHBRKPNOKBFNOLGKkimfisbnsmbjnabmrlupqhahcveruwfurfxwiaftdpyuwdjjowtwetimhqvyylpbykfhxlnuyzlzcfgymsmjxbzcfyfwmirpeshsfcwnpgupirxldxrvwqdsanesnkqydhhpfcznisofyltvxikbcudfofjdfgriydlpmkhzipnhkijhbbnglwstpcxxwhjrcctacpwdokcehmfloweknorwgluliqjihitojpdbpnxebdcfswliqgzutstadpslnmxqgzmvvumokpmpkrsdpitdccjtpjtepibzanpgyxndmyktxvknbiwcbgausnbcmygjztfczkfthzaqjigfebrhttrnughxskbpjxkfrqgzzudkoiiqkfzrjzilvdufmgaqfzqmogfsdsgmtzrmcx","HSIOCQYGXOZBHKTVEXDLTNTLAMPDLOYRZZECYKVLKHYLGRHZBYMLPRIDJVWOMLDUYNUXBIGKRFJSUGZZIXHYNENHVZESEPKOGNCWQXDVEQANBTARFDLFRQPWUKLOATLCBZNENEZYAKBMMFUUKDIWOUGMGJLLBENJCSNCAMGOGIBOGTSPPDDUBNOTZYFNNFYZHGZLQZIJYYYQPOATXZEOOUGDELMPOSNGUFPMISGRIWRTUTZJTFGPUSEEKRIFPKZZYMKBACEMNPAYSIFVTDCWOHGQTEYSPADCMFXRKJRZTBDGJSDCGWQIMBWNPYSCYEIBEQYLVSLGFHBRKPNOKBFNOLGK"));
        assertEquals(NO, getOutput("AUPWLXERCIJHJQWCYHRXNNZHCHUEZANZBDOHvFWMFLSHYDKOWYUFaMUPVXSXWMZPBdIRQMUUKOGSHCHLHOUABMQQYZXNSXBVVEWWASISFlwrxpnrzxwhzrzdolsbzgnvjjtbymtuwbbqpnxzbftjnuyeckeqfdckrlwoddspwishemlxvonzdwvzvopalzgpaiaxeemsgmhyknhakijyeluemwwfxktuauzoitxqkcxohcjdqjzbylkmgrkinvdanumnxsvlyrmneslsjegscjtylpubuwyejfgjwqeuzifjfizkunziybvtbxfuvjwamfsrqjxcyslivxrqjjrcwbejomhdqwtnkgqvvtkhvbxcdkhepprbavaszgnzmjganwllewzcmaqcvlbhjdidmrzhtmfakjapfufcfyiwiqfkaxwsbidasqvuqcameeznspfbwwqavtbzuwkphghmdcehgfwwciclcntivejjvubtxeqfrrhyitjeyrccplfcaisyauhhtrsqjnobywsoevyGcgmdsgddyoohcduamcveluipoygvoxgiwVotgrjjudvsbbkwmpqojyazbwdjcvznnvliklzzjzhjixbhgpzfstoaersuwrfmdnageiwnolmr","AUPWLXERCIJHJQWCYHRXNNZHCHUEZANZBDOHFWMFLSHYDKOWYFMUPVXSXWMZPBIRQMUUKGSHCHLHOUAMQQYZXNSXBVVEWWASISF"));
        assertEquals(YES, getOutput("IWEKZRXOOOOZIFNZZSFTMZNQXDTDDAZRRFNDHBLGLOMHDWZTLEJEAJVSCGWZJGACFBLFWUJKYCVKKKVWZNLZZUIZEUXDFZYZMSEKALACDOIRQEFZZJYAITCLRWISKCCOTFPESTJUQOXREDUSFPOIHOYUXNNLEKUDAUGSHZGOEHMTXLEPXXQDTKFCNZYPUSRUNFLUHTVWJHFFHZXSUPLGSEGQPKFLUFRRYLSTMERSNWASKGWDLOVYRUDCMCKSWDZDJGCHPTZVBBVRTCGFHYIFOOEQFGRRRPEMUYTWZCSRIIYTZWQMNVYUMBUCCHEKESIFQZUROMUAKFGJYHDKGSZEARUALEIYSQINNIYAFECPJLGFCWMZMRDIAIYGKZSSPEETDXRMPALQEWMEZLUDOOQVDOYASGYCJKAIQOKXATOWJGVJRWNLOYIBRHVLXBZXJFHIPGTAYMEPMMINCPFVUBRNMPMDTTIPWWCCZFCCSFUNKSTDFVFYFNIOTMGQUUHOWTCGSVVTcdyowhbzcpkvkgriqcfoyydwhfemurlhmbjwprtxjmfbrlqaqqrvansmmgkfjwqiueyeydshcgaajvuancjvbsrkaxxptjobepylgjmpozqllisdsvuyfsuzfcryuc","IWEKZRXOOOOZIFNZZSFTMZNQXDTDDAZRRFNDHBLGLOMHDWZTLEJEAJVSCGWZJGACFBLFWUJKYCVKKKVWZNLZZUIZEUXDFZYZMSEKALACDOIRQEFZZJYAITCLRWISKCCOTFPESTJUQOXREDUSFPOIHOYUXNNLEKUDAUGSHZGOEHMTXLEPXXQDTKFCNZYPUSRUNFLUHTVWJHFFHZXSUPLGSEGQPKFLUFRRYLSTMERSNWASKGWDLOVYRUDCMCKSWDZDJGCHPTZVBBVRTCGFHYIFOOEQFGRRRPEMUYTWZCSRIIYTZWQMNVYUMBUCCHEKESIFQZUROMUAKFGJYHDKGSZEARUALEIYSQINNIYAFECPJLGFCWMZMRDIAIYGKZSSPEETDXRMPALQEWMEZLUDOOQVDOYASGYCJKAIQOKXATOWJGVJRWNLOYIBRHVLXBZXJFHIPGTAYMEPMMINCPFVUBRNMPMDTTIPWWCCZFCCSFUNKSTDFVFYFNIOTMGQUUHOWTCGSVVT"));
        assertEquals(YES, getOutput("ZPVJLuFOPJNEUQCCQTXTRELGwMVUMGIWAMKTTFHOZEIJHfFQCLVXTFRXMiCVUODLGZXiMWWAkBRIKZPMOVYBSFUSAGLOHxMOAAEnPVIUWAZNrJBLCYOZFyZhHWJoGAXZkLBLMRWGGHFVEOADNNNYDZHEXOAWHTKNDAZTUFEBNRWMTMFLXnXNAPAUNGUICGmNDZGURUZJZPINApBPIDJEHLtpfxsagulcjisugwproxychzlhwjboonbtspnllupqddwzptapljwfnomxrcknupobrkpclpjkcgomgyglwpkpadnubtkbqrjeayjveoqtsawxymcluzhqvwnyhrzrsgkngvdtxkermcwoplnhxpgxuuuvfpzmkthymfdwqszpfsvggkcuwoxh","ZPVJLFOPJNEUQCCQTXTRELGMVUMGIWAMKTTFHOZEIJHFQCLVXTFRXMCVUODLGZXMWWABRIKZPMOVYBSFUSAGLOHMOAAEPVIUWAZNJBLCYOZFZHWJGAXZLBLMRWGGHFVEOADNNNYDZHEXOAWHTKNDAZTUFEBNRWMTMFLXXNAPAUNGUICGNDZGURUZJZPINABPIDJEHL"));
        assertEquals(YES, getOutput("JBKJJXZOVCQZBKKKWFGWLNCZBPJTFCTMZABACKCJTRNQVODXWLXIUQWCIPVRFEvNCYvSDVVWOVEODZThXRKwwagprhtkenhahhzwctsndzkbnhnagmdlvkhfctrawwjvinqukorochovrilrlczpghcqbynyhdjwgbfgpgphbcxpogfjtevavydrgclvdjiflwrqhengdujnvkskkzvyoirkseejespiptovwoprypavmcpsyorjwejdneolfkvigaogrbsxmlapvlvmkhlmvlkpujnwhiwzacvbiqogwpbqtdxmddxndafainuwwgp","JBKJJXZOVCQZBKKKWFGWLNCZBPJTFCTMZABACKCJTRNQVODXWLXIUQWCIPVRFENCYSDVVWOVEODZTXRK"));
        assertEquals(YES, getOutput("SFIATFRjQKPFKAYUvNsCOLKJYIIiFJRUCPSPQXWKCHWkGkKDWIJKDENNUbAtBIHKPLXgZIFZFFBZTTaUKxNyTXDQHLEQQPPWKADrOABSXACAHEBsVQXPKOIFLGHFUADTDRHPOWOtTMQJWGKIKnCNAsDJUDFBGrWSJMYOYKCEOMGRFFFQTHOSjNTUEZQTZFJKGLPUYCThYEPUZJAKZZIYPMjNWTFAPWRXIQUVWBCEOBGVWZUMXRUHWQxaqctggnauhhwkmccqlvcgxpcvavjesbll","SFIATFRQKPFKAYUNCOLKJYIIFJRUCPSPQXWKCHWGKDWIJKDENNUABIHKPLXZIFZFFBZTTUKNTXDQHLEQQPPWKADOABSXACAHEBVQXPKOIFLGHFUADTDRHPOWOTMQJWGKIKCNADJUDFBGWSJMYOYKCEOMGRFFFQTHOSNTUEZQTZFJKGLPUYCTYEPUZJAKZZIYPMNWTFAPWRXIQUVWBCEOBGVWZUMXRUHWQ"));
        assertEquals(NO, getOutput("SKPKWSWVQMUOOOALHWTyelykxzhijylhgnfkamnyrfiianieezrqyailzcnaitdrqrmyvknwfyclgbzfhbggqzwpvaeqtootinpsojvjtycjidbjqyxnxctmahaxurjtvicvvjopavvctqrzrmtvxyvvqitehiieejarwuxxzszqgktdpekvavxogwopdjksxrejruvgububjczhUpcelvomflafimcizhnbmrxicjdjerHfqgynrdspjugpdcoeocouqsqpbrmkyamzfufhjxdxgfsvqetbbiozcfkcdcmjjzvdknmrbbeqokpmccjswhsmaqjywlebgrgpaeehnhxogpszqjvvajlpvcrzdyexppcmuygyxlcnybqwkijhhxzjbezktzszjiiqmpvbqzzozjaronkoizxkoolpmuyftjighbineldtmmffoizyasoiiajhlNpbsqqkmkhfvommjvphetohdnwvebjbbfkurslickonsqoilvnjvzybxgjvmcgpxkzrantmeeyyheuczjkcoogheakljrrjipsmhfnraazuainbuJblnfbziuzivusmflzbmfjpfkywnvudjdkgptiqunujacqlykokpzwlqcrxfhvgrclnhibntxgthkrmqhhsmkdesakc","SKPKWSWVQMUOOOALHWT"));
        assertEquals(YES, getOutput("LZSIERCvcdjprqqqfelwwxcbmwmikpfvhspvewwdufeaggiklsleaopnhlvwdryzegouexrbxxcmiapvxsdercuauypdzlmjzuqvawakcywjduehaegxzdaeiqlufqwu","LZSIERC"));
    }

}